apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: infra-challenge
data:
  postgres-init.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(200) NOT NULL UNIQUE
    );

    INSERT INTO users (name, email)
    VALUES
        ('Alice', 'alice@example.com'),
        ('Bob', 'bob@example.com')
    ON CONFLICT (email) DO NOTHING;
